; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32c6

[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = 
	colorize
	default
board_build.partitions = partitions_zigbee.csv
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DZIGBEE_MODE_ED
	-DARDUINO_USB_CDC_ON_BOOT=0
	-IC:/Users/cq/.platformio/packages/esp-zigbee-sdk/components/esp-zigbee-lib/include
	-LC:/Users/cq/.platformio/packages/esp-zigbee-sdk/components/esp-zigbee-lib/lib/esp32c6
	-lesp_zb_api.ed
	-lzboss_port.native
	-IC:/Users/cq/.platformio/packages/esp-zboss-lib/include
	-LC:/Users/cq/.platformio/packages/esp-zboss-lib/lib/esp32c6
	-lzboss_stack.ed
upload_speed = 921600
lib_deps = adafruit/DHT sensor library@^1.4.7
build_type = release

[env:dev]
extends = env:esp32c6
build_type = debug
build_flags = 
	${env:esp32c6.build_flags}
	-DCORE_DEBUG_LEVEL=3
	-DDEBUG_ENABLED
lib_deps = adafruit/DHT sensor library@^1.4.7
